Repository helloworldjay/Cryptocurrency, pull requests merged in 2022-02, with the labels that each got.

#32 [#30] SegmentedControl의 Index로 PaymentCurrency가 결정되는 기능을 구현해요
  Bithumb/Bithumb.xcodeproj/project.pbxproj
  Bithumb/Bithumb/Exchange/Components/CoinList/CoinListView.swift
  Bithumb/Bithumb/Exchange/Components/CoinList/CoinListViewModel.swift
  Bithumb/Bithumb/Exchange/Components/ExchangeSearchBar/ExchangeSearchBar.swift
  Bithumb/Bithumb/Exchange/Components/ExchangeSearchBar/ExchangeSearchBarViewModel.swift
  Bithumb/Bithumb/Exchange/Components/ExchangeSegmentedControl/SegmentedCategoryView.swift
  Bithumb/Bithumb/Exchange/Components/ExchangeSegmentedControl/SegmentedCategoryViewModel.swift
  Bithumb/Bithumb/Exchange/ExchangeViewController.swift
  Bithumb/Bithumb/Exchange/ExchangeViewModel.swift
  Bithumb/Bithumb/Network/NetworkManager.swift
  Bithumb/BithumbTests/Exchange/Components/SegmentedCategory/SegmentedCategoryViewTests.swift
  Bithumb/BithumbTests/Exchange/ExchangeViewModelTests.swift
  Bithumb/BithumbTests/Exchange/Spy/ExchangeUseCaseSpy.swift
Labels: feature

#31 [#25] ChartData를 구현하고 CoinDetailViewController에 Chart를 배치해요
  Bithumb/Bithumb.xcodeproj/project.pbxproj
  Bithumb/Bithumb/CoinDetail/ChartData.swift
  Bithumb/Bithumb/CoinDetail/CoinDetailViewController.swift
  Bithumb/Bithumb/CoinDetail/CoinDetailViewModel.swift
  Bithumb/Bithumb/CoinDetail/Components/TimeInterval.swift
  Bithumb/Bithumb/CoinDetail/Components/TimeIntervalBottomSheet.swift
  Bithumb/Bithumb/CoinDetail/Components/TimeIntervalViewModel.swift
  Bithumb/Bithumb/Resources/Extensions/Array + Ext.swift
  Bithumb/Bithumb/Resources/Module/BottomSheet.swift
  Bithumb/Podfile
  Bithumb/Podfile.lock
Labels: feature

#35 [#33] Web Socket 통신을 위한 기반 작업을 해요
  Bithumb/Bithumb.xcodeproj/project.pbxproj
  Bithumb/Bithumb/Entity/SocketTickerResponse.swift
  Bithumb/Bithumb/Exchange/Components/CoinList/CoinListViewModel.swift
  Bithumb/Bithumb/Network/WebSocketManager.swift
  Bithumb/Podfile
  Bithumb/Podfile.lock
Labels: feature

#52 [#51] Conflict 해결시 발생한 문제 해결
  Bithumb/Bithumb/Exchange/ExchangeViewModel.swift
Labels: bug

#53 [#2] 프로젝트 설명 문서를 작성해요
  Documents/Conventions.md
  README.md
Labels: documentation

#60 [#59] REST API를 통해서 가상화폐 상세화면의 호가정보를 출력해요
  Cryptocurrency/Cryptocurrency.xcodeproj/project.pbxproj
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailUseCase.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailViewController.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailViewModel.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/CurrentPriceStatusView/CoinPriceData.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/CurrentPriceStatusView/CurrentPriceStatusView.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/CurrentPriceStatusView/CurrentPriceStatusViewModel.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/OrderBookListView/OrderBookListView.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/OrderBookListView/OrderBookListViewCell.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/OrderBookListView/OrderBookListViewCellData.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/OrderBookListView/OrderBookListViewModel.swift
  Cryptocurrency/Cryptocurrency/Entity/OrderBookResponse.swift
  Cryptocurrency/Cryptocurrency/Resources/Extensions/String + Ext.swift
  Cryptocurrency/CryptocurrencyTests/CoinDetail/CoinDetailUseCaseTests.swift
  Cryptocurrency/CryptocurrencyTests/CoinDetail/Spy/NetworkManagerSpy.swift
Labels: feature

#63 [#62] 시세정보를 나타낼 시세창의 UI를 구현하고, 화면에 시세정보를 출력해요
  Cryptocurrency/Cryptocurrency.xcodeproj/project.pbxproj
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailCategory.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailUseCase.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailViewController.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailViewModel.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/CoinChartView/CoinChartView.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/CoinChartView/CoinChartViewModel.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/CoinDetailSegmentedCategoryView/CoinDetailSegmentedCategoryView.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/CoinDetailSegmentedCategoryView/CoinDetailSegmentedCategoryViewModel.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/CurrentPriceStatusView/CurrentPriceStatusViewModel.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/OrderBookListView/OrderBookCategory.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/OrderBookListView/OrderBookListView.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/OrderBookListView/OrderBookListViewModel.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/TransactionSheetView/TransactionSheetView.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/TransactionSheetView/TransactionSheetViewCell.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/TransactionSheetView/TransactionSheetViewCellData.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/TransactionSheetView/TransactionSheetViewModel.swift
  Cryptocurrency/Cryptocurrency/Resources/Base.lproj/LaunchScreen.storyboard
  Cryptocurrency/CryptocurrencyTests/CoinDetail/CoinDetailUseCaseTests.swift
Labels: feature

#64 [#61] 코인 정보 결과물을 정렬할 수 있는 기능을 구현하고 화면에 적용해요
  Cryptocurrency/Cryptocurrency.xcodeproj/project.pbxproj
  Cryptocurrency/Cryptocurrency/Exchange/Components/CoinList/CoinListView.swift
  Cryptocurrency/Cryptocurrency/Exchange/Components/CoinList/CoinListViewModel.swift
  Cryptocurrency/Cryptocurrency/Exchange/Components/CoinListSort/CoinListSortCriterion.swift
  Cryptocurrency/Cryptocurrency/Exchange/Components/CoinListSort/CoinListSortView.swift
  Cryptocurrency/Cryptocurrency/Exchange/Components/CoinListSort/CoinListSortViewModel.swift
  Cryptocurrency/Cryptocurrency/Exchange/ExchangeUseCase.swift
  Cryptocurrency/Cryptocurrency/Exchange/ExchangeViewController.swift
  Cryptocurrency/Cryptocurrency/Exchange/ExchangeViewModel.swift
  Cryptocurrency/Cryptocurrency/Resources/Module/SortButton.swift
  Cryptocurrency/CryptocurrencyTests/Exchange/ExchangeUseCaseTests.swift
  Cryptocurrency/CryptocurrencyTests/Exchange/ExchangeViewModelTests.swift
  Cryptocurrency/CryptocurrencyTests/Exchange/Spy/ExchangeUseCaseSpy.swift
Labels: feature

#66 [#65] 가상화폐 상세화면에 소켓을 연결하여 실시간 업데이트를 수행해요
  Cryptocurrency/Cryptocurrency.xcodeproj/project.pbxproj
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailCoordinator.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailUseCase.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailViewModel.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/CurrentPriceStatusView/CurrentPriceStatusView.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/OrderBookListView/OrderBookCategory.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/OrderBookListView/OrderBookListView.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/OrderBookListView/OrderBookListViewCellData.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/OrderBookListView/OrderBookListViewModel.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/TransactionSheetView/TransactionSheetViewCell.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/TransactionSheetView/TransactionSheetViewCellData.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/TransactionSheetView/TransactionSheetViewModel.swift
  Cryptocurrency/Cryptocurrency/Entity/SocketOrderBookResponse.swift
  Cryptocurrency/Cryptocurrency/Entity/SocketTickerResponse.swift
  Cryptocurrency/Cryptocurrency/Entity/SocketTransactionResponse.swift
  Cryptocurrency/Cryptocurrency/Exchange/Components/CoinList/CoinListViewModel.swift
  Cryptocurrency/Cryptocurrency/Network/WebSocketManager.swift
  Cryptocurrency/Cryptocurrency/Resources/Extensions/Array + Ext.swift
  Cryptocurrency/Cryptocurrency/Resources/Extensions/Double + Ext.swift
  Cryptocurrency/CryptocurrencyTests/CoinDetail/CoinDetailUseCaseTests.swift
  Cryptocurrency/CryptocurrencyTests/Exchange/Components/CoinListView/CoinListViewModelTests.swift
Labels: feature

#71 [#70] 앱의 시그니쳐 색깔 등 일부 변경 작업과 Launch Screen을 구현 작업을 해요
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailCoordinator.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/CoinDetailViewController.swift
  Cryptocurrency/Cryptocurrency/CoinDetail/Components/CurrentPriceStatusView/CurrentPriceStatusView.swift
  Cryptocurrency/Cryptocurrency/Exchange/Components/ExchangeSearchBar/ExchangeSearchBar.swift
  Cryptocurrency/Cryptocurrency/Exchange/ExchangeCoordinator.swift
  Cryptocurrency/Cryptocurrency/Resources/Assets.xcassets/appIcon.imageset/Contents.json
  Cryptocurrency/Cryptocurrency/Resources/Assets.xcassets/appIcon.imageset/appIcon.png
  Cryptocurrency/Cryptocurrency/Resources/Base.lproj/LaunchScreen.storyboard
  Cryptocurrency/Cryptocurrency/Resources/Coordinators/AppCoordinator.swift
  Cryptocurrency/Cryptocurrency/Resources/Extensions/UIColor + Ext.swift
  Cryptocurrency/Cryptocurrency/TBD/CurrentAsset/CurrentAssetCoordinator.swift
  Cryptocurrency/Cryptocurrency/TBD/MoreOption/MoreOptionCoordinator.swift
  Cryptocurrency/Cryptocurrency/TBD/ProductService/ProductServiceCoordinator.swift
  Cryptocurrency/Cryptocurrency/TBD/Transaction/TransactionCoordinator.swift
Labels: feature
